# Generated by Django 3.0.3 on 2020-04-06 04:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREM', 'Premium')], default='FREE', max_length=4, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
