# Generated by Django 3.0.4 on 2020-04-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='quiz.CategoryQuiz', verbose_name='Category'),
        ),
    ]
