# Generated by Django 3.0.5 on 2020-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='answer_correct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='The answers are correct'),
        ),
    ]
