# Generated by Django 3.0.5 on 2020-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_transcript_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total questions'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='answer_correct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total number of correct answers'),
        ),
    ]
