# Generated by Django 3.0.5 on 2020-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200428_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='total_score',
            field=models.FloatField(default=0, verbose_name='Total score'),
        ),
    ]
