# Generated by Django 3.0.5 on 2020-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200428_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='publish',
            field=models.BooleanField(blank=True, default=False, help_text='If yes, the quiz is displayed in the quiz list', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Clean URL'),
        ),
    ]
