# Generated by Django 3.0.5 on 2020-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200501_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(),
        ),
    ]
