# Generated by Django 3.0.5 on 2020-05-11 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200511_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='transcript_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
