# Generated by Django 3.0.5 on 2020-05-12 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='document',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
