# Generated by Django 3.0.3 on 2020-04-06 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docatago',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='document',
            name='catago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docum.Docatago', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, to='docum.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
