# Generated by Django 3.0.5 on 2020-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0002_auto_20200529_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publish',
            field=models.BooleanField(blank=True, default=False, help_text='If yes, the material is displayed in the material list', verbose_name='Publish'),
        ),
    ]
