# Generated by Django 3.0.5 on 2020-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0003_document_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='backup_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Backup link'),
        ),
    ]
