# Generated by Django 3.0.3 on 2020-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0003_auto_20200406_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
