# Generated by Django 3.0.3 on 2020-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0004_auto_20200407_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
