# Generated by Django 3.0.3 on 2020-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0006_auto_20200408_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='doc_items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='docum.Document', verbose_name='Items'),
        ),
    ]
